# Production
FROM node:16.13.2-alpine AS production

WORKDIR /pong/front-end

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --configuration=production

# Nginx
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=production /pong/front-end/dist/front-end /usr/share/nginx/html
COPY --from=production /pong/front-end/nginx/nginx.conf /etc/nginx/conf.d/default.conf
#
#EXPOSE 80

#CMD ["nginx", "-g", "daemon off;"]
